id: composer-config

info:
  name: composer-config-file
  author: Mahendra Purbia (Mah3Sec_)
  severity: info
  tags: config,exposure

requests:
  - method: GET
    headers:
      Proxy-Host: 127.0.0.1
      Real-Ip: 127.0.0.1
      X-Client-IP: 127.0.0.1
      X-Custom-IP-Authorization: 127.0.0.1
      X-Forwarded: 127.0.0.1
      X-Forwarded-By: 127.0.0.1
      X-Forwarded-For: 127.0.0.1
      X-Forwarded-For-Original: 127.0.0.1
      X-Forwarded-Host: 127.0.0.1
      X-Forwarded-Port: 127.0.0.1
      X-Forwarded-Server: 127.0.0.1
      X-Forwarder-For: 127.0.0.1
      X-Forward-For: 127.0.0.1
      X-Host: 127.0.0.1
      X-Http-Destinationurl: 127.0.0.1
      X-Http-Host-Override: 127.0.0.1
      X-Original-Remote-Addr: 127.0.0.1
      X-Original-Url: 127.0.0.1
      X-Originating-IP: 127.0.0.1
      X-Proxy-Url: 127.0.0.1
      X-Real-Ip: 127.0.0.1
      X-Remote-Addr: 127.0.0.1
      X-Remote-IP: 127.0.0.1
      X-Rewrite-Url: 127.0.0.1
    path:
      - "{{BaseURL}}/composer.json"
      - "{{BaseURL}}/composer.lock"
      - "{{BaseURL}}/.composer/composer.json"
      - "{{BaseURL}}/vendor/composer/installed.json"

    matchers:
      - type: dsl
        name: composer.lock
        dsl:
          - "contains(body, 'packages') && contains(tolower(all_headers), 'application/octet-stream') && status_code == 200"

      - type: dsl
        name: composer.json
        dsl:
          - "contains(body, 'require') && contains(tolower(all_headers), 'application/json') && status_code == 200"
