id: laravel-env

info:
  name: Laravel .env file accessible
  author: pxmme1337,dwisiswant0,geeknik,emenalf,adrianmf
  severity: critical
  description: Laravel uses the .env file to store sensitive information like database credentials and tokens. It should not be publicly accessible.
  reference: https://laravel.com/docs/master/configuration#environment-configuration
  tags: config,exposure,laravel

requests:
  - method: GET
    headers:
      Proxy-Host: 127.0.0.1
      Real-Ip: 127.0.0.1
      X-Client-IP: 127.0.0.1
      X-Custom-IP-Authorization: 127.0.0.1
      X-Forwarded: 127.0.0.1
      X-Forwarded-By: 127.0.0.1
      X-Forwarded-For: 127.0.0.1
      X-Forwarded-For-Original: 127.0.0.1
      X-Forwarded-Host: 127.0.0.1
      X-Forwarded-Port: 127.0.0.1
      X-Forwarded-Server: 127.0.0.1
      X-Forwarder-For: 127.0.0.1
      X-Forward-For: 127.0.0.1
      X-Host: 127.0.0.1
      X-Http-Destinationurl: 127.0.0.1
      X-Http-Host-Override: 127.0.0.1
      X-Original-Remote-Addr: 127.0.0.1
      X-Original-Url: 127.0.0.1
      X-Originating-IP: 127.0.0.1
      X-Proxy-Url: 127.0.0.1
      X-Real-Ip: 127.0.0.1
      X-Remote-Addr: 127.0.0.1
      X-Remote-IP: 127.0.0.1
      X-Rewrite-Url: 127.0.0.1
    path:
      - "{{BaseURL}}/.env"
      - "{{BaseURL}}/.env.dev.local"
      - "{{BaseURL}}/.env.development.local"
      - "{{BaseURL}}/.env.prod.local"
      - "{{BaseURL}}/.env.production.local"
      - "{{BaseURL}}/.env.local"
      - "{{BaseURL}}/.env.example"
      - "{{BaseURL}}/.env.stage"
      - "{{BaseURL}}/.env.live"
      - "{{BaseURL}}/.env.backup"
      - "{{BaseURL}}/.env.save"
      - "{{BaseURL}}/.env.old"
      - "{{BaseURL}}/.env_1"
      - "{{BaseURL}}/.env_sample"
      - "{{BaseURL}}/api/.env"

    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - "(?mi)^APP_(NAME|ENV|KEY|DEBUG|URL|PASSWORD)="
          - "(?mi)^DB_(HOST|PASSWORD|DATABASE)="
        condition: or

      - type: status
        status:
          - 200
