id: server-private-keys

info:
  name: Detect Private SSH, TLS, and JWT Keys
  author: geeknik
  severity: high
  tags: config,exposure

requests:
  - method: GET
    headers:
      Proxy-Host: 127.0.0.1
      Real-Ip: 127.0.0.1
      X-Client-IP: 127.0.0.1
      X-Custom-IP-Authorization: 127.0.0.1
      X-Forwarded: 127.0.0.1
      X-Forwarded-By: 127.0.0.1
      X-Forwarded-For: 127.0.0.1
      X-Forwarded-For-Original: 127.0.0.1
      X-Forwarded-Host: 127.0.0.1
      X-Forwarded-Port: 127.0.0.1
      X-Forwarded-Server: 127.0.0.1
      X-Forwarder-For: 127.0.0.1
      X-Forward-For: 127.0.0.1
      X-Host: 127.0.0.1
      X-Http-Destinationurl: 127.0.0.1
      X-Http-Host-Override: 127.0.0.1
      X-Original-Remote-Addr: 127.0.0.1
      X-Original-Url: 127.0.0.1
      X-Originating-IP: 127.0.0.1
      X-Proxy-Url: 127.0.0.1
      X-Real-Ip: 127.0.0.1
      X-Remote-Addr: 127.0.0.1
      X-Remote-IP: 127.0.0.1
      X-Rewrite-Url: 127.0.0.1
    path:
      - "{{BaseURL}}/localhost.key"
      - "{{BaseURL}}/host.key"
      - "{{BaseURL}}/www.key"
      - "{{BaseURL}}/private-key"
      - "{{BaseURL}}/privatekey.key"
      - "{{BaseURL}}/server.key"
      - "{{BaseURL}}/my.key"
      - "{{BaseURL}}/key.pem"
      - "{{BaseURL}}/ssl/localhost.key"
      - "{{BaseURL}}/ssl/{{Hostname}}.key"
      - "{{BaseURL}}/id_rsa"
      - "{{BaseURL}}/id_dsa"
      - "{{BaseURL}}/.ssh/id_rsa"
      - "{{BaseURL}}/.ssh/id_dsa"
      - "{{BaseURL}}/{{Hostname}}.key"
      - "{{BaseURL}}/{{Hostname}}.pem"
      - "{{BaseURL}}/config/jwt/private.pem"
      - "{{BaseURL}}/jwt/private.pem"
      - "{{BaseURL}}/var/jwt/private.pem"
      - "{{BaseURL}}/private.pem"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "BEGIN OPENSSH PRIVATE KEY"
          - "BEGIN PRIVATE KEY"
          - "BEGIN RSA PRIVATE KEY"
          - "BEGIN DSA PRIVATE KEY"
          - "BEGIN EC PRIVATE KEY"
          - "BEGIN PGP PRIVATE KEY BLOCK"
        condition: or

      - type: status
        status:
          - 200

      - type: dsl
        dsl:
          - '!contains(body_2, "<html")'
          - '!contains(body_2, "<HTML")'
        condition: and
