id: ssh-authorized-keys

info:
  name: SSH Authorized Keys
  author: geeknik
  reference: https://www.ssh.com/academy/ssh/authorized-key
  severity: low
  tags: config,exposure,ssh

requests:
  - method: GET
    headers:
      Proxy-Host: 127.0.0.1
      Real-Ip: 127.0.0.1
      X-Client-IP: 127.0.0.1
      X-Custom-IP-Authorization: 127.0.0.1
      X-Forwarded: 127.0.0.1
      X-Forwarded-By: 127.0.0.1
      X-Forwarded-For: 127.0.0.1
      X-Forwarded-For-Original: 127.0.0.1
      X-Forwarded-Host: 127.0.0.1
      X-Forwarded-Port: 127.0.0.1
      X-Forwarded-Server: 127.0.0.1
      X-Forwarder-For: 127.0.0.1
      X-Forward-For: 127.0.0.1
      X-Host: 127.0.0.1
      X-Http-Destinationurl: 127.0.0.1
      X-Http-Host-Override: 127.0.0.1
      X-Original-Remote-Addr: 127.0.0.1
      X-Original-Url: 127.0.0.1
      X-Originating-IP: 127.0.0.1
      X-Proxy-Url: 127.0.0.1
      X-Real-Ip: 127.0.0.1
      X-Remote-Addr: 127.0.0.1
      X-Remote-IP: 127.0.0.1
      X-Rewrite-Url: 127.0.0.1
    path:
      - "{{BaseURL}}/.ssh/authorized_keys"
      - "{{BaseURL}}/_/.ssh/authorized_keys"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "ssh-dss"
          - "ssh-ed25519"
          - "ssh-rsa"
          - "ecdsa-sha2-nistp256"
        condition: or

      - type: status
        status:
          - 200
